services:
  - type: web
    name: natomanga-graphql-api # Name of the service
    env: docker
    repo: https://github.com/IamHomen/NatoManga-GraphQL-API.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 4000
